// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.ccae.dcx.lcc.sm.curso;

import br.ufpb.ccae.dcx.lcc.sm.curso.Disciplina;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Disciplina_Roo_Configurable {
    
    declare @type: Disciplina: @Configurable;
    
}
